# 调用堆栈

## 调用栈

JavaScript只是一段代码，而真正决定Javascript如何运行的是Javascript解释器。下面不再强调和区分这一概念。

如果JavaScript代码在运行的时候遇到了一个函数的调用，解释器会把这个函数放到一个栈中，如果函数中又调用了一个函数，解释器也会把这个刚被调用的函数放入栈中。这个栈叫调用栈（call stack）。JavaScript是单线程的，意味着调用栈只有一个。

调用函数时，该函数入栈。函数执行完毕时，该函数出栈。

[Call stack（调用栈） - 术语表 | MDN (mozilla.org)](https://developer.mozilla.org/zh-CN/docs/Glossary/Call_stack)

实际上，解释器在将函数压入调用栈前会先为函数创建一个调用环境，再把调用环境（而不是单纯一个函数）压入栈中。这部分知识了解即可。

[[译\] 理解 JavaScript 中的执行上下文和执行栈 - 掘金 (juejin.cn)](https://juejin.cn/post/6844903682283143181)

## 堆栈追踪

调用栈的元素叫调用帧。

某个函数发生异常时，你可能在浏览器的控制台看到类似报错：（在文件foo.js中，函数start中调用了函数bar，在函数bar中调用了一次foo，foo发生了异常）![img](https://p1-jj.byteimg.com/tos-cn-i-t2oaga2asx/gold-user-assets/2017/11/11/f6e50bf394efe82889e3a53b788a46fc~tplv-t2oaga2asx-zoom-in-crop-mark:4536:0:0:0.awebp)

因为解释器执行代码时把函数的调用都放入了调用栈中，所以一个调用帧有异常，我们可以知道异常的位置以及调用这一发生异常的函数的所有祖先函数。这就是堆栈追踪。

## 堆栈溢出

调用栈的空间是有限的，存入超量的调用帧将会抛出一个“堆栈溢出”异常。实践中很少发生这种情况，但你仍需要考虑你的所有递归函数引发堆栈溢出的可能。

## 事件循环

JavaScript是单线程的，也就是说JavaScript只能在同一时间真正执行一个任务。运行任务需要花费的时间有长有短，如果在代码中按照从上到下的顺序执行代码，会带来糟糕的用户体验。

可以简单（但不准确）地认为，执行时间短的任务叫同步任务，执行时间长的任务叫异步任务。解释器先执行完同步任务，再执行异步任务。在这个过程中，仍然是单线程的。

![img](https://p1-jj.byteimg.com/tos-cn-i-t2oaga2asx/gold-user-assets/2017/11/21/15fdd88994142347~tplv-t2oaga2asx-zoom-in-crop-mark:4536:0:0:0.image)